### ISSUE TITLE
[FEATURE] Style standardization

### ISSUE THREAD

**Issue by shurwit** [rokwire/illinois-app#3221]
**Is your feature request related to a problem? Please describe.**
We currently have a long list of redundant and unnecessary style definitions (eg. colors, text styles, icons... etc.). 

**Describe the solution you'd like**
We should work towards standardizing and reducing the list of styles to a manageable common set.

**Additional context**
Color changes to make (discussed with @vburgett):

- [ ] Delete mango #F29835 from the json file.
- [ ] Apply "fillColorSecondary" to instances of "accentColor1" and delete "accentColor1" (both are "#E84A27") from the json file.
- [ ] Change eventColor to a new value #E84A27 (current value: "eventColor" "#E54B30")
- [ ] Replace three instances of "textSurfaceAccent" with "textBackground" (same color #404040), and delete "textSurfaceAccent" from json file.
- [ ] Delete "textbackgroundVariant"  "#404040" from json file since there are no instances in the app.
- [ ] Until we have an overall agreement on naming conventions, let's replace all instances of "textSurface": "#404040" with "textBackground": "#404040", and delete "textSurface": "#404040"  from the json file.

**Comment by vburgett** [comment]
Updated to exclude a few of the above items since time has passed. Let's make the below three updates only.

- [ ] Delete mango #F29835 from the json file.
- [ ]  Change eventColor to a new value #E84A27 (current value: "eventColor" "#E54B30")
- [ ]  Delete "textbackgroundVariant" "#404040" from json file since there are no instances in the app.
